name: Manual plan

on:
    workflow_dispatch:
        inputs:
            branch:
                required: true
                type: string
            DEV:
                required: true
                type: boolean
            STG:
                required: true
                type: boolean
            PROD:
                required: true
                type: boolean
            eu-central-1:
                required: true
                type: boolean
            eu-west-1:
                required: true
                type: boolean
            us-east-1:
                required: true
                type: boolean
            us-west-2:
                required: true
                type: boolean
            module:
                required: true
                type: choice
                options:
                    - alation/catalog
                    - alation/analytics
                    - astronomer
                    - aws
                    - datadog
                    - dataiku
                    - datalake
                    - ecr
                    - github_actions
                    - iam
                    - jenkins_node
                    - jumpserver
                    - qlik
                    - securecore
                    - snowflake
                    - ssm
                    - ssm_patch_manager
                    - vpc
            target:
                type: string

jobs:
    run-manual-workflow:
        runs-on: ubuntu-latest
        steps:
          - name: Print inputs
            shell: bash
            run: |
              echo "running on ${{ inputs.branch }} for module ${{ inputs.module }} with target ${{ inputs.target }}"