name: "💡 Feature Request"

description: Suggest a new feature that we could implement!
labels: ["enhancement"]

body:
  - type: dropdown
    id: workflow_type
    attributes:
      label: "Workflow"
      description: In which automation you want this feature?
      multiple: false
      options:
        - Terraform
        - Snowflake
        - JSM/JIRA
        - Repository Management
        - Other
    validations:
      required: true
  - type: input
    id: other_type
    attributes:
      label: "Other"
      description: If you selected Other, please specify in which automation or tool you need this feature
      placeholder: ex. resource-finder/runner-checker/snowflake_user_list_clone
    validations:
      required: false
  - type: textarea
    id: what
    attributes:
      label: "What"
      description: Please enter an explicit description of your idea
      placeholder: Description of your idea...
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: "Why"
      description: Please enter why this feature is important to you and what does it solve
      placeholder: Description of why this feature is important and what does it solve...
    validations:
      required: true