name: "🐛 Bug Report"

description: Create a new ticket for a bug. Help us improve!
title: "🐛 <title>"
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: "Describe the bug"
      description: Please enter an explicit description of your issue.
      placeholder: Description of your incident...
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected behavior"
      description: A clear and concise description of what you expected to happen.
      placeholder: Description of what you expected to happen...
    validations:
      required: true
  - type: input
    id: workflow_url
    attributes:
      label: "Workflow run URL"
      description: Please enter your Workflow run URL to provide a reproduction of the issue
      placeholder: ex. https://github.com/ORG/REPO-NAME/actions/runs/RUN-NUMBER
    validations:
      required: true
  - type: checkboxes
    id: environments
    attributes:
      label: "Which environments the bug was found"
      description: In which environments you had this bug?
      options:
        - label: dev
        - label: stg
        - label: prod
        - label: custodian
  - type: checkboxes
    id: regions
    attributes:
      label: "Which regions the bug was found"
      description: In which regions you had this bug?
      options:
        - label: us-west-2
        - label: eu-central-1
        - label: us-east-1
        - label: eu-west-1
  - type: textarea
    id: reproduction_steps
    attributes:
      label: "Reproduction steps"
      description: If applicable, the steps to reproduce the behavior
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional context"
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: bash
    validations:
      required: false
