name: "🐛 Bug Report"

description: Create a new ticket for a bug. Help us improve!
title: "🐛 <title>"
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: "Describe the bug"
      description: Please enter an explicit description of your issue.
      placeholder: Description of your incident...
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected behavior"
      description: A clear and concise description of what you expected to happen.
      placeholder: Description of what you expected to happen...
    validations:
      required: true
  - type: input
    id: workflow_url
    attributes:
      label: "Example workflow run URL"
      description: Please enter a Workflow run URL to provide an example of the issue
      placeholder: ex. https://github.com/ORG/REPO-NAME/actions/runs/RUN-NUMBER
    validations:
      required: true
  - type: dropdown
    id: environments
    attributes:
      label: "Which environments the bug was found"
      description: In which environments you had this bug?
      multiple: true
      options:
        - Dev
        - Stg
        - Prod
        - Custodian
        - Not on an specific environment
    validations:
      required: false
  - type: dropdown
    id: regions
    attributes:
      label: "Which regions the bug was found"
      description: In which regions you had this bug?
      multiple: true
      options:
        - us-west-2
        - eu-central-1
        - us-east-1
        - eu-west-1
        - Not on an specific region
    validations:
      required: false
  - type: textarea
    id: reproduction_steps
    attributes:
      label: "Reproduction steps"
      description: If applicable, the steps to reproduce the behavior
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional context"
      description: Add any other context about the problem here.
    validations:
      required: false
