name: "Module Identifier"
description: "This action has the purpose of identifying which module is being modified in a Pull Request"

inputs: 
  token:
    description: "The space webhook URL"
    required: true
  repo:
    description: "Mention people or not, format <users/user_id>"
    default: 'wexinc/ps-ds-platform-eng-iac'
  pull_number:
    description: "Pull Request number"
    required: true
  

runs:
  using: 'composite'

  steps:
    - name: Identify Module
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        REPO: ${{ inputs.repo }}
        PULL_NUMBER: ${{ inputs.pull_number }}
      working-directory: ${{ github.action_path }}/src
      run: |-
        python3 -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
        python module_identifier.py
        deactivate
        rm -rf .venv
