name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set-2
    steps:
    - run: lsb_release -a
    - run: free
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - uses: hashicorp/setup-terraform@v3
    - run: terraform -v
