name: DEV - test pull request

on:
    pull_request:
        paths:
            - '**/dev-*.tfvars'

jobs:
    test_pull_request_path:
        runs-on: ubuntu-latest

        steps:
            - name: print something
              run: |
                echo ${{ toJson(github.event) }}