name: DEV - test pull request

on:
    pull_request:
        paths:
            - '**/dev-*.tfvars'

jobs:
    test_pull_request_path:
        runs-on: ubuntu-latest

        steps:
          - name: checkout
            uses: actions/checkout@v4

          - uses: ./.github/actions/module_identifier
            id: module_identifier
            with:
                token: ${{ secrets.GITHUB_TOKEN }}
                repo: ${{ github.event.repository.full_name }}
                pull_number: ${{ github.event.number }}

          - name: Print module
            run: |-
              echo "Module: ${{ steps.module_identifier.outputs.module_name }}"