name: "[TF][AUTO] - [DEV][US-WEST-2]"
run-name: "[ ${{ github.event.pull_request.head.ref }} ] - Pull Request: ${{ github.event.action }}"

on:
    pull_request:
        types: [opened, synchronize, reopened, closed]
        branches: dev
        paths:
            - '**/dev-us-west-2.tfvars'

jobs:
    identify_module:
      runs-on: ubuntu-latest
      outputs:
        module_name: ${{ steps.module_identifier.outputs.module_name }}
      steps:
        - name: Checkout action
          id: checkout_code
          if: startsWith(github.head_ref, 'gha_beta/')
          uses: actions/checkout@v4
          with:
            sparse-checkout: .github/actions

        - name: Identify module
          id: module_identifier
          if: startsWith(github.head_ref, 'gha_beta/')
          uses: ./.github/actions/module_identifier
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            repo: ${{ github.event.repository.full_name }}
            pull_number: ${{ github.event.number }}


    execution:
        runs-on: ubuntu-latest
        needs: [identify_module]
        steps:
          - name: Checkout action
            id: checkout_code
            if: startsWith(github.head_ref, 'gha_beta/')
            uses: actions/checkout@v4

          - name: Plan
            if: |
              startsWith(github.head_ref, 'gha_beta/') 
              && github.event.action != 'closed'
            run: |
              cd ${{ needs.identify_module.outputs.module_name }}
              tree

          - name: Apply
            if: |
              startsWith(github.head_ref, 'gha_beta/') 
              && github.event.action == 'closed'
              && github.event.pull_request.merged == true
            run: |
              cd ${{ needs.identify_module.outputs.module_name }}
              tree