name: DEV - test pull request

on:
    pull_request:
        types: [opened, synchronize, reopened, closed]
        branches: dev
        paths:
            - '**/dev-*.tfvars'

jobs:
    test_pull_request_path:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout
            if: startsWith(github.head_ref, 'gha_beta/')
            uses: actions/checkout@v4

          - name: Identify module
            if: startsWith(github.head_ref, 'gha_beta/')
            uses: ./.github/actions/module_identifier
            id: module_identifier
            with:
                token: ${{ secrets.GITHUB_TOKEN }}
                repo: ${{ github.event.repository.full_name }}
                pull_number: ${{ github.event.number }}

          - name: Print module
            if: |
              startsWith(github.head_ref, 'gha_beta/') 
            run: |-
              echo "Module: ${{ steps.module_identifier.outputs.module_name }}"
              pwd
              echo "${{ toJson(github.event.pull_request) }}"

          - name: On Merge Only
            if: |
              startsWith(github.head_ref, 'gha_beta/') 
              && github.event.pull_request.merged == true
            run: |
              echo "Merged"