name: "Test"

on:
    workflow_dispatch:

jobs:
    test:
        runs-on: dev
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: test action
              id: test_action  
              uses: ./.github/actions/test-action
            - name: outputs
              env:
                OUTPUT_1: ${{ steps.test_action.outputs.test }}
                OUTPUT_2: ${{ steps.test_action.outputs.test2 }}
                MULTILINE_OUTPUT: ${{ steps.test_action.outputs.test_multiline }}
              run: |
                echo $OUTPUT_1
                echo $OUTPUT_2
                echo $MULTILINE_OUTPUT
                echo ${{ steps.test_action.outputs.test_multiline }}
