name: test reusable
on: [push]

jobs:
    test:
      uses: ./.github/workflows/tf-plan.yml
      with:
        module: "aws"
        target: 'module.test.est'
        environment: DEV
        region: us-west-2