name: "Test"

on:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: test action
              id: test_action  
              uses: ./.github/actions/test-action
            - name: outputs
              run: |
                echo ${{ steps.test_action.outputs.test }}
                echo ${{ steps.test_action.outputs.test2 }}
