name: Pull Request Checks

on:
  pull_request:
    branches: dev

jobs:
  check_if_branch_is_ahead_of_dev:
    runs-on: ubuntu-latest
    name: Check if branch is ahead of dev
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check if branch is ahead of dev
        run: |
          if ! git merge-base --is-ancestor origin/dev ${{ github.event.pull_request.head.sha }};
          then echo "This branch is not up to date with main";
          exit 1; fi
